### ISSUE TITLE
[ISSUE] Instant game crash when landing on any Planet.

### ISSUE THREAD

**Issue by reverentfeynmen** [ReadOnlyDevelopment/Interstellar-Exoplanets#45]
## Issue Report (Not for Crashes - Please use Crash Report template for crashes)
[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

[ #### Important:
 - If you decide to delete this template entirely, your issue will be closed. 
 - If you do not provide relevant information when reporting an issue (for example experiencing a bug or glitch and not providing your latest.log or relevant log) this issue will be closed.
### Please use [This Haste Server](https://haste.romvoid.dev) to paste ANY logs as these are set to never expire. ]

[ #### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. 
If you are using an unofficial version of Exoplanets please report it to the person who gave you the version. Also please look at the other issues to make sure that you are not creating a duplicate. ]

#### What you expected to happen:
I expected to land on an Exo Planet but instead I got an ERROR Game crashed!
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (Galacticraft-1.12.2-4.0.6.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 5/2/24 3:45 PM
Description: Unexpected error

java.lang.AbstractMethodError: asmodeuscore.core.astronomy.sky.SkyProviderBase.getAtmosphereColor()Lnet/minecraft/util/math/Vec3d;
	at asmodeuscore.core.astronomy.sky.SkyProviderBase.render(SkyProviderBase.java:494)
	at net.minecraft.client.renderer.RenderGlobal.func_174976_a(RenderGlobal.java:1274)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1296)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at asmodeuscore.core.astronomy.sky.SkyProviderBase.render(SkyProviderBase.java:494)
	at net.minecraft.client.renderer.RenderGlobal.func_174976_a(RenderGlobal.java:1274)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1296)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['SR8TLine'/0, l='MpServer', x=308.50, y=900.00, z=-620.50]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [GCEntityClientPlayerMP['SR8TLine'/0, l='MpServer', x=308.50, y=900.00, z=-620.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1477771016 bytes (1409 MB) / 2089287680 bytes (1992 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m
	IntCache: cache: 0, tcache: 62, allocated: 1, tallocated: 14
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version      | Source                            | Signature                                |
	|:------ |:------------------- |:------------ |:--------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2       | minecraft.jar                     | None                                     |
	| LCHIJA | mcp                 | 9.42         | minecraft.jar                     | None                                     |
	| LCHIJA | FML                 | 8.0.99.99    | forge-1.12.2-14.23.5.2860.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2860 | forge-1.12.2-14.23.5.2860.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | micdoodlecore       | 4.0.6        | minecraft.jar                     | None                                     |
	| LCHIJA | galacticraftcore    | 4.0.6        | Galacticraft-1.12.2-4.0.6.jar     | None                                     |
	| LCHIJA | galacticraftplanets | 4.0.6        | Galacticraft-1.12.2-4.0.6.jar     | None                                     |
	| LCHIJA | asmodeuscore        | 1.0.1        | AsmodeusCore-1.12.2-1.0.1.jar     | None                                     |
	| LCHIJA | exoplanets          | 0.1.4        | Interstellar-Exoplanets-0.1.4.jar | 3a39a2b4e84bec377849d48f372382b39f883e16 |
	| LCHIJA | spaceambient        | 0.0.1        | SpaceAmbient-1.12.2-0.0.1.jar     | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (Galacticraft-1.12.2-4.0.6.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 551.61' Renderer: 'NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2'
	Launched Version: forge-14.23.5.2860
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 551.61, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Interstellar Exoplanets.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor 

#### Important Versions Info (Do *not* use "latest"):

- Minecraft:
- Forge:
- Exoplanets: 
- Galacticraft:
- Using a server (yes/no): 
  - If yes, are any Server API's used, what version? (ex: Sponge): 
- List any Galacticraft Addons w/ versions:
  - Addons:

#### Your most recent log file where the issue was present: 

[ haste.romvoid.dev link here ]

**Comment by reverentfeynmen** [comment]
I can't delete my issue report!

**Comment by reverentfeynmen** [comment]
Fix the crash by disabeling Render Body and Render Atmosphere.
